### ISSUE TITLE
calc_fishing_mortality

### ISSUE THREAD

**Issue by quantifish** [seacode/gmacs#131]
Needs a good look over. Here is the header and and issue at the bottom

	 * @brief Calculate fishing mortality rates for each fleet.
	 * @details For each fleet estimate scaler log_fbar and deviates (f_devs).
         *
         * dmr is the discard mortality rate
	 * 
	 * In the event that there is effort data and catch data, then it's possible
	 * to estimate a catchability coefficient and predict the catch for the
	 * period of missing catch/discard data.  Best option for this would be
	 * to use F = q*E, where q = F/E.  Then in the objective function, minimize
	 * the variance in the estimates of q, and use the mean q to predict catch.
	 * Or minimize the first difference and assume a random walk in q.
	 * 
	 * Note that this function calculates the fishing mortality rate including
	 * deaths due to discards.  Where xi is the discard mortality rate.
	 * 
	 * Note also that Jie estimates F for retained fishery, f for male discards and
	 * f for female discards.  Not recommended to have separate F's for retained and 
	 * discard fisheries, but might be ok to have sex-specific F's.  
	 * 
	 * TODO 
	 * -[ ] fix discard mortality rate.

**Comment by wStockhausen** [comment]
Darcy,

Discussing fishing mortality rates in Gmacs is somewhat problematic because
we keep mixing CAPTURE rates and mortality rates. The Gmacs fishing
mortality equations are based on fishery CAPTURE rates, size-specific
capture selectivity functions, size-specific retention functions, and
discard mortality rates. There are no "discard mortality" F's that are
being estimated "separately"--these are calculated based on the estimated
capture rates, etc. If Jie is estimating discard mortality rates (for
males) directly as parameters somehow, then this represents a substantial
difference between his model and Gmacs--and not one (in my opinion) that
Gmacs should try to accomodate.

Buck

***************************************************
* Dr. William T. Stockhausen                      *
***************************************************
* Resource Ecology and Fisheries Management       *
* Alaska Fisheries Science Center                 *
* National Marine Fisheries Service               *
* National Oceanic and Atmospheric Administration *
* 7600 Sand Point Way N.E.                        *
* Seattle, Washington 98115-6349                  *
***************************************************
* email: William.Stockhausen@noaa.gov             *
* voice: 206-526-4241 fax: 206-526-6723           *
* web  : http://www.afsc.noaa.gov                 *
***************************************************
All models are wrong, some are useful.--G.E.P. Box
Beware of geeks bearing equations.    --W. Buffett
***************************************************
Disclaimer: The opinions expressed above are personal
and do not necessarily reflect official NOAA policy.

**Comment by smartell** [comment]
Regarding the TODO. I neglected to X that one out.  I had originally had a fixed dmr in the code and wanted to fix it such that it was a user input.
